/**
 * Single source of truth for template-text locales (top 25 world languages).
 * Generates:
 *   public/i18n/templates/index.json          (manifest for client + server)
 *   src/lib/design/i18n/locales.ts            (typed manifest for the app code)
 * Run: bun scripts/i18n-locales.mjs
 */
import fs from "node:fs"

export const LOCALES = [
  { code: "en", en: "English", native: "English", dir: "ltr" },
  { code: "zh", en: "Chinese (Simplified)", native: "简体中文", dir: "ltr" },
  { code: "hi", en: "Hindi", native: "हिन्दी", dir: "ltr" },
  { code: "es", en: "Spanish", native: "Español", dir: "ltr" },
  { code: "fr", en: "French", native: "Français", dir: "ltr" },
  { code: "ar", en: "Arabic", native: "العربية", dir: "rtl" },
  { code: "bn", en: "Bengali", native: "বাংলা", dir: "ltr" },
  { code: "pt", en: "Portuguese", native: "Português", dir: "ltr" },
  { code: "ru", en: "Russian", native: "Русский", dir: "ltr" },
  { code: "ur", en: "Urdu", native: "اردو", dir: "rtl" },
  { code: "id", en: "Indonesian", native: "Bahasa Indonesia", dir: "ltr" },
  { code: "de", en: "German", native: "Deutsch", dir: "ltr" },
  { code: "ja", en: "Japanese", native: "日本語", dir: "ltr" },
  { code: "mr", en: "Marathi", native: "मराठी", dir: "ltr" },
  { code: "te", en: "Telugu", native: "తెలుగు", dir: "ltr" },
  { code: "tr", en: "Turkish", native: "Türkçe", dir: "ltr" },
  { code: "ta", en: "Tamil", native: "தமிழ்", dir: "ltr" },
  { code: "vi", en: "Vietnamese", native: "Tiếng Việt", dir: "ltr" },
  { code: "tl", en: "Filipino", native: "Filipino", dir: "ltr" },
  { code: "ko", en: "Korean", native: "한국어", dir: "ltr" },
  { code: "it", en: "Italian", native: "Italiano", dir: "ltr" },
  { code: "fa", en: "Persian", native: "فارسی", dir: "rtl" },
  { code: "th", en: "Thai", native: "ไทย", dir: "ltr" },
  { code: "sw", en: "Swahili", native: "Kiswahili", dir: "ltr" },
  { code: "pl", en: "Polish", native: "Polski", dir: "ltr" },
]

const outDir = new URL("../public/i18n/templates/", import.meta.url)
fs.mkdirSync(outDir, { recursive: true })
fs.writeFileSync(new URL("index.json", outDir), JSON.stringify({ version: 1, locales: LOCALES }, null, 2))

const ts = `/**
 * GENERATED by scripts/i18n-locales.mjs — do not edit by hand.
 * Template-text localization locales (top 25 world languages).
 */
export interface TemplateLocale {
  code: string
  en: string
  native: string
  dir: "ltr" | "rtl"
}

export const TEMPLATE_LOCALES: TemplateLocale[] = ${JSON.stringify(LOCALES, null, 2)}

export const TEMPLATE_LOCALE_CODES = TEMPLATE_LOCALES.map((l) => l.code)

export function isTemplateLocale(code: string | null | undefined): code is string {
  return !!code && TEMPLATE_LOCALE_CODES.includes(code)
}

export function templateLocaleByCode(code: string): TemplateLocale | undefined {
  return TEMPLATE_LOCALES.find((l) => l.code === code)
}
`
fs.mkdirSync(new URL("../src/lib/design/i18n/", import.meta.url), { recursive: true })
fs.writeFileSync(new URL("../src/lib/design/i18n/locales.ts", import.meta.url), ts)
console.log(`manifest written: ${LOCALES.length} locales`)
